[package]
name = "libsodium-sys"
version = "0.1.0+1.0.18"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.65.1"
pkg-config = "0.3.27"
